# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  platform: 'Any CPU'
  configuration: 'Release'
  projectPath: 'BlazorLeaflet/BlazorLeaflet/BlazorLeaflet.csproj'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    configuration: $(configuration)
    projects: $(projectPath)

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    configuration: $(configuration)
    packagesToPack: $(projectPath)
    nobuild: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.artifactstagingdirectory)'
    artifactName: 'BlazorLeaflet'
  condition: succeededOrFailed()

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c627ab72-9d60-49a3-884b-ef9d060fb5c5/a74d2c1b-3b9f-42dd-9748-fcd6f6daf7d9'